#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd -- "$repo_dir"
umask 077

for directory in config data; do
  if [[ -L "$directory" ]]; then
    printf 'Refusing symlink directory: %s\n' "$directory" >&2
    exit 1
  fi
  mkdir -p -- "$directory"
  chmod 700 -- "$directory"
done

if [[ -e config/.env || -L config/.env ]]; then
  if [[ ! -f config/.env || -L config/.env ]]; then
    printf 'config/.env must be a regular file, not a symlink.\n' >&2
    exit 1
  fi
  chmod 600 -- config/.env
  printf 'Kept existing config/.env; no settings or tokens were replaced.\n'
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  printf 'openssl is required. Install it with your Linux package manager, then rerun this script.\n' >&2
  exit 1
fi

api_token="$(openssl rand -hex 32)"
admin_token="$(openssl rand -hex 32)"

# noclobber also protects against another initializer creating the file meanwhile.
(
  set -o noclobber
  cat > config/.env <<EOF
# Generated by scripts/init-dushengtv.sh. Keep this file private.
TOKEN=$api_token
ADMIN_TOKEN=$admin_token
FAVORITE_REQUIRE_ADMIN=true
LOCAL_DANMU_NOT_REQUIRE_ADMIN=false
SOURCE_ORDER=local,douban,360,tencent,youku,iqiyi,imgo,bilibili
DANMU_OUTPUT_FORMAT=json
LOG_LEVEL=warn
LOCAL_CACHE_ENABLED=true
SEARCH_CACHE_MINUTES=10
COMMENT_CACHE_MINUTES=10
DUSHENGTV_CACHE_ENABLED=true
DUSHENGTV_CACHE_DAYS=14
DUSHENGTV_CACHE_MAX_MB=512
RATE_LIMIT_MAX_REQUESTS=30
REMEMBER_LAST_SELECT=false
USE_BANGUMI_DATA=false
EOF
)
chmod 600 -- config/.env
printf 'Created config/.env with separate random API and admin tokens.\n'
printf 'Created data/ for persistent cache and local danmu.\n'
printf 'Next: docker compose up -d --build\n'
